//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdondathang
    {
        public int IDdonhang { get; set; }
        public int IDsp { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> tongtien { get; set; }
    
        public virtual thongtinmathang thongtinmathang { get; set; }
    }
}
